### ISSUE TITLE
Offer forward compatibility

### ISSUE THREAD

**Issue by pascaldekloe** [pascaldekloe/colfer#11]
Unmarshalling can skip unknown fields / headers when the binary's size is known.
-- @awalterschulze

**Comment by awalterschulze** [comment]
Dont forget about nested messages :)

**Comment by mzaks** [comment]
Shouldn't it skip till it finds `0x7f`. In case of nested structs while scanning to `0x7f` keep track that the field id keep increasing. If they decrease than previous struct was not closed properly. It still could result in cases where it would be hard to say which struct was not closed properly, but I think it should be manageable price to pay compared to benefits provided by forward compatibility.

**Comment by pascaldekloe** [comment]
@mzaks, we cannot read until `0x7f` because it might be a value in the data itself.

**Comment by mzaks** [comment]
Ops :)
you are right.

**Comment by pascaldekloe** [comment]
Forward compatibility is a go.

**Comment by awalterschulze** [comment]
Awesome. Do you have some link to a diff or spec?

**Comment by pascaldekloe** [comment]
The second draft lives in the v2 branche at https://github.com/pascaldekloe/colfer/blob/v2/SPEC.md.

**Comment by pascaldekloe** [comment]
The fixed size acts as a version number. Since the `embedded` tail is written in reverse order you can skip unknown data. Still need to do a lot of explaining in the specification.

**Comment by awalterschulze** [comment]
Yes, I think what would help me understand, is an example, which includes some new unknown fields and some old removed fields.
Very exciting to see that you might have figured it out :)

**Comment by pascaldekloe** [comment]
Field removal is not an option with this construction. The compiler can ommit the respective fields buy they will be included as the zero value in the serial, which is one byte for most.

**Comment by awalterschulze** [comment]
Ok fair, but I will be able to send more fields than the receiver expects and also receive less fields than I expect, right?  Your caveat is that these fields need to be at the end of the defined message, which is still fair in terms of backwards and forwards compatibility, since that is your rule.

**Comment by pascaldekloe** [comment]
Yes, correct. These embedded blobs also allow optimisations such as a single malloc for multiple strings and such. An example will follow in the spec.
