### ISSUE TITLE
why not making colf java based on annotation processing

### ISSUE THREAD

**Issue by stephanenicolas** [pascaldekloe/colfer#15]
`@Colfer` could be used to identify pojo classes. Then the annotation processor would scan the class and generate the code for serialization / deserialization.

This is the most popular java way to do it. Annotation processors are a standard part of the java compiler.

Colf has a great potential on Android. And annotation processors are very common in Android builds.

**Comment by pascaldekloe** [comment]
Are you proposing to derive the schema from annotated bean properties? I understand why this seems appealing to a Java-centric environment.

The response will be a bit slow because I have no access to a computer for a while.

**Comment by stephanenicolas** [comment]
Yes I do. Members don't even need to be annotated, only the pojo class
itself would need to be annotated to be visible to the annotation
processor, then you scan the field and infer the schema.

2017-01-14 5:10 GMT-08:00 Pascal S. de Kloe <notifications@github.com>:

**Comment by pascaldekloe** [comment]
Sounds like a good plan. Do you have an example project which you like? I found plenty of documentation on the annotation processor itself.

I'm looking for a job now. If your company hires me it'll be done in no time. Otherwise the ETA is April.

**Comment by stephanenicolas** [comment]
We hire Android devs at Groupon, and web devs, Java, Js, etc.
Look at https://jobs.groupon.com/
Let me know if you are interested.

If you go to my GH page, you can find a few examples of libs using
annotation processing : Toothpick, Dart, BoundBox in order of the most
recent I coded.


2017-01-15 6:08 GMT-08:00 Pascal S. de Kloe <notifications@github.com>:

**Comment by pascaldekloe** [comment]
Now with the Maven plugin and super class support the usecases for annotation processing are all gone I think.

**Comment by stephanenicolas** [comment]
@pascal, can you ad a link please ?

2017-04-29 23:17 GMT+02:00 Pascal S. de Kloe <notifications@github.com>:

**Comment by stephanenicolas** [comment]
I am not sure about the new technology you mention, but it seems to me that
incremental compilation can only be performed via annotation processing.

2017-04-30 10:31 GMT+02:00 Stéphane NICOLAS <steff.nicolas@gmail.com>:

**Comment by pascaldekloe** [comment]
True. The incremental steps also add a ton of issues so it should be worth the trouble.

For the compilation to be part of the build just use the Maven plugin and to customise code apply a parent class with the `-x` flag.

https://github.com/pascaldekloe/colfer/blob/master/java/maven/src/main/java/net/quies/colfer/maven/CompileMojo.java#L73

What other usecases can you think of?
