### ISSUE TITLE
[JAVA] NPE if I try to serialize an object with a null property

### ISSUE THREAD

**Issue by Blakko** [pascaldekloe/colfer#17]
During the marshalling this part throws the NPE

```java
if (!this.property.isEmpty()) {
```

**Comment by pascaldekloe** [comment]
In my opinion `null` is overused in Java. As a result null checks are everywhere.

You are talking about strings. Is it not better to do the check at the place where the null pointer comes from? This isolates the issue and optimises controlled flows.

**Comment by Blakko** [comment]
I'm not sure i understand what you're suggesting.
Let's say i have a class with 2 `String` properties. One of them mandatory and the second one optional. I would expect the second one to be null if not set.
How would you handle such a case?

**Comment by pascaldekloe** [comment]
Unset strings are empty (`""`) in Colfer objects. To check whether a field is defined you can use `String#isEmpty()`.

Yes there are very rare cases where you want to distinguish between undefined and no value. Then you can add a boolean to make it explicit. It's actually faster too, also in terms of serialisation.

**Comment by Blakko** [comment]
Now i get it thanks. I'll just check to not set null properties as you suggested for now, i don't think i have to distinguish null from empty strings atm.
