### ISSUE TITLE
Compiler generates non compiling code (Java)

### ISSUE THREAD

**Issue by jschneider** [pascaldekloe/colfer#2]
I tried it with the downloaded compiler and this colf file:

package asdf

type PrimArraysColfer struct {
    id    []uint64
    time    []uint64
    valueInteger    []int32
    valueInteger64    []int64
    valueFloat    []float32
    valueDouble    []float64
}

**Comment by pascaldekloe** [comment]
Number arrays are on the TODO list. The compiler's error reporting could use an upgrade though. ^_^

**Comment by pascaldekloe** [comment]
Floating point lists are done now @jschneider.
