### ISSUE TITLE
Timezone offset for Go

### ISSUE THREAD

**Issue by dahankzter** [pascaldekloe/colfer#27]
It would be great if this could be supported. Right now I have to serialise extra fields to rematerialize it correctly.

I think, unless it is very hard, that I can give it a stab if you point me in the right direction.

**Comment by pascaldekloe** [comment]
The timestamp has no timezone on purpose as the data type is ment to determine a moment as efficient as possible. Also the nanosecond resolution seems unlikely to be usefull in combination with a local date-time representation.

I think it is good practice to leave the time zone up to the user interface where possible. If you need a gregorian calendar how about ISO strings? I find them easy to use and if you have to allocate a string anyway then the overhead is quite low, especially with the "basic format" as in `20170512T1639+0100`.

As far as I know there are no numeric ways to represent a timezone thanks to daylight saving time. An if it has to be a token then which standard should one use?

**Comment by pascaldekloe** [comment]
I have a hard time understanding why people use city names for timezone identification. Even when you get rid of the redundant continent prefix the identifiers are way too long. And even better, they sometimes change over time. :joy:
https://en.m.wikipedia.org/wiki/Tz_database

**Comment by pascaldekloe** [comment]
https://en.m.wikipedia.org/wiki/Time_zone After reading all that I don't think we'll manage a solid solution and I refuse to let coders suffer the consequences. My advise is to use a nice JavaScript library in the frontend or store the string as an additional field like you do now. Sorry.

**Comment by dahankzter** [comment]
I understand the problems you are facing but this is not about simple view rendering. We are ingesting high volume of date stamped data and would like to use colfer instead of json for some parts that need to be fast. It requires rematerializing the timestamped data at the other end of a Kafka stream for further processing. This processing then uses this date to lookup data which is where the problem happens. The order is preserved so thats fine but equality is not afaik (needs some testing). There are workarounds of course and if the producing app had used say UTC from the start it would have work out of the box.

**Comment by pascaldekloe** [comment]
Indeed Colfer works well with Kafka due it size efficiency. It sounds like you are using a timestamp as a key which is fine. However timezoned keys are a recepy for trouble. Is `20170514T23:35+01` equal to `20170514T22:35Z`? Also (timezone) strings ruin your performance.

**Comment by dahankzter** [comment]
Indeed I will have to do some thinking here.
Easiest seems to be to use int64 + int offset if I can get the db equality
to work.

**Comment by dahankzter** [comment]
Actually it seems to work... Some more testing is needed but the database comparison seems to properly compare UTC to whatever a particular row has. :)
