### ISSUE TITLE
Simple usage example

### ISSUE THREAD

**Issue by condolina** [pascaldekloe/colfer#28]
I am interested in seeing a simple Java code example that uses Colfer for serialization into a ByteStream. I am currently conducting a study on the energy efficiency of serialization/deserialization on Android devices, specifically with regards to large numerical data types such as vectors, and will like to include Colfer in my study. Short of asking @eishay, and because it will provide a quick head-start,  a link to a very basic use case would be appreciated.

**Comment by pascaldekloe** [comment]
For Java it is literally one function call as in `colferObj.marshal(out, null)`. Of course reuse of the returned buffer helps efficiency. See the generated JavaDoc for details.
