### ISSUE TITLE
JS version works wrong

### ISSUE THREAD

**Issue by kutase** [pascaldekloe/colfer#29]
Hi. I have a problem with generated JS code. I use Golang as a server and JS as client. Golang version makes valid marshal and unmarshal. JS version returns wrong packet after unmarshalling of packet from Golang server.
It's my code:

```go
type update struct {
	id uint16
	x float32
	y float32
	rotation float32
	DT float32
	HP uint8
	commandId uint32
	maxBulletId uint16
}

type update_arr struct {
	packetType uint8
	players []update
}
```

Exactly **update_arr** packet works wrong in JS version.

On Golang server I have this data:
```javascript
{
  "id": 0,
  "x": 100,
  "y": 100,
  "rotation": 0,
  "DT": 0,
  "HP": 100,
  "commandId": 0,
  "maxBulletId": 0
}
```

But on JS client:
```javascript
{
  "id": 0,
  "x": 2.4262940954800533e35,
  "y": -131072.03125,
  "rotation": 0,
  "DT": 0,
  "HP": 100,
  "commandId": 0,
  "maxBulletId": 0
}
```

**Comment by pascaldekloe** [comment]
That sounds unfortunate @kutase. Are all fields off or is it a specific one?
Unfortunately I'm on a holiday until the 26th. Maybe I can convince a friend to bring a laptop on the 8th and fix things then.

**Comment by kutase** [comment]
@pascaldekloe thank you for so fast response. This issue arise only on nested fields like **players** in  **update_arr** packet. Flat packets like **update** works fine.

**Comment by pascaldekloe** [comment]
Good to know. :-) I'll have access to a computer on the 9th and will fix it then.

**Comment by pascaldekloe** [comment]
I missed the offset on the buffer for JavaScript. Please let me know if you need a release urgently. Otherwise I'll finnish the holidays first.

**Comment by kutase** [comment]
@pascaldekloe thank you for fix. I'm not need a release urgently.
