### ISSUE TITLE
Question: why not just use a subset of Go as the IDL?

### ISSUE THREAD

**Issue by h12w** [pascaldekloe/colfer#31]
The IDL is so similar to Go. Why not just use a subset of Go directly? e.g.

* time.Time for timestamp
* []byte for binary

**Comment by pascaldekloe** [comment]
The words timestamp and binary clearly indicate the nature of the data. An array of bytes may not be appropriate to all languages. Tokens like time.Time look weird to a C developer. And how about the following?

```
type plan struct {
	phases []time.block
	created time.Time
}
```

**Comment by h12w** [comment]
I agree that time.Time looks weird.

[]byte should be fine. One-to-one translation is not mandatory for all languages.

BTW, why text rather than string?

**Comment by pascaldekloe** [comment]
String is a mathematical name for a sequence. One could argue that the binary is a string.

I want to make it crystal clear that the type is about the content. For example Java gets text as an object with UTF-16. Go's UTF-8 equivalent is a different string for the same text.
