### ISSUE TITLE
EBNF Spec Needed

### ISSUE THREAD

**Issue by h12w** [pascaldekloe/colfer#32]
The current [spec](https://github.com/pascaldekloe/colfer/wiki/Spec) is ambiguous. e.g.

"Data structures consist of zero or more field value definitions followed by a termination byte 0x7f."

* Data structures: why the plural? Colfer is one data structure or consecutive data structures in a stream? 
* the whole format is terminated by 0x7f or each of the field followed by 0x7f? (I guess the former)

Could you please write an EBNF spec? EBNF is unambiguous and uses less characters than descriptions. A good example is [The Go Programming Language Specification](https://golang.org/ref/spec).

**Comment by pascaldekloe** [comment]
Sounds like a sane idea. I updated the wiki too. Feel free to adjust things to your likings.

```ebnf
struct :≡ def* 127
def :≡ header data
header :≡ key o̅r̅ flagged-key
key :≡ 0 – 126
flagged-key :≡ 128 – 254
```
