### ISSUE TITLE
Im interested in using colfer for a project... how stable is this project?

### ISSUE THREAD

**Issue by rucuriousyet** [pascaldekloe/colfer#33]
I am building a big/important project and I need a stable option for serialization. I am considering Msgpack and Protobuf as alternatives but Colfer has a nice schema and seems to be more performant. How stable/maintained is this project, would you say its production ready?

Thanks!

**Comment by pascaldekloe** [comment]
The Java and Go code has been battle-tested. Some people reported success with JavaScript. The C version is quite new and I would love some feedback.

As you can see in the issue tracker bugs are fixed well within 24 hours so yes, the project is stable and well maintained, if I may say so myself.
