### ISSUE TITLE
Segmentation fault in a unique case

### ISSUE THREAD

**Issue by ks228** [pascaldekloe/colfer#34]
Hi,
I hope all are great. 

Scenario:
I have the following mapping in my chappee.colf file.

package chappee
type mappee {
   maptype uint32
   msgtype uint32
   callmsg   text
    debugleve  text
    minseed  uint64
    maxseed  uint64
}

During packing, if I set the last two values, the packing is successful. 
Now, if during packing I pack first 4 (or any of them) and don't pack the last 2, I get a segmentation fault. 
I think it would be great that Colfer itself should take care of the values which are not set. 

It can be taken as a bug, or it can be taken as a feature request. 

Cheers,
infoginx.com

**Comment by pascaldekloe** [comment]
Sounds aweful @ks228. Let's fix that right away. Which language are you compiling to? I'll be home in a few hours.

**Comment by ks228** [comment]
I am using C. I haven't tested on other languages yet.

**Comment by pascaldekloe** [comment]
Ofcourse, it's the new kid in town. (see #33)
So to be precise, calling chappee_mappee_marshal with `&chappee_mappee{.maptype = 42}`  segfaults even when `buf` is large enough, correct?

**Comment by ks228** [comment]
I am doing the following
void* buf = malloc(colfer_size_max);

Seems like large enough given very few values in the colf type.

**Comment by pascaldekloe** [comment]
Perfect! That case should be safe for any positive value of colfer_size_max.

**Comment by pascaldekloe** [comment]
Can't reproduce the segmentation fault @ks228. This is what I did.

```colfer
package chappee

type mappee struct {
	maptype   uint32
	msgtype   uint32
	callmsg   text
	debugleve text
	minseed   uint64
	maxseed   uint64
}
```

```C
#include "build/issue34/Colfer.h"

#include <stdio.h>
#include <stdlib.h>

int main() {
	void* buf = malloc(colfer_size_max);

	printf("TEST issue 34 marshal\n");
	struct chappee_mappee x = {.maptype = 42};
	size_t n = chappee_mappee_marshal(&x, buf);
	if (n != 3) {
		printf("got size %zu, want 3\n", n);
		return 1;
	}

	free(buf);
}
```

**Comment by ks228** [comment]
My code is running in a loop and finds this problem when it is running. Sometimes it does in the first iteration as well. 
Also, I am using the colf-linux 1.6

My system specs are 
Linux client-4 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

If you have tested it on the latest version then I think I should move to the latest one. Otherwise run it in a loop e.g. a loop of say 2000 iterations, with random numbers. 

Strange bit for me is that once I have set all the values in the type, I did not get any seg fault. But if I miss out the bottom ones, I get the seg fault (only when running against multiple values but all those values which are being added to type values don't have gibberish etc values).

**Comment by pascaldekloe** [comment]
I have a hard time imagining how the values could influence each other since the marshaling for each member is done in a separate code block. The only way for a segmentation fault I see is when the string sizes are out of bounds. That is the struct is not properly initialized and either `chappee_mappee.callmsg.len` or `chappee_mappee.debugleve.len` are not zero. Can you please share the code which initiates the `chappee_mappee` struct?

**Comment by ks228** [comment]
Here is the example from my code. You need to now think of cmsd instead of chappee. Or forget the chappee mappee from above. 

Here is my cms.colf

```
package cmsd

type map_cap struct {
        msgtype uint32
        mapid   uint32
        cip     text
        eip     text
        minseed uint64
        maxseed uint64
        prefix  text
}
```

This code gives seg. 

```
size_t pack_map_with_colfer(uint32_t mapid, char* cip, char* eip, char* buf){
        cmsd_map_cap* m = malloc(sizeof(cmsd_map_cap));
        m->msgtype = (uint32_t)0;
        m->mapid = (uint32_t)mapid;
        m->cip.utf8 = malloc(strlen(cip)+1);
        m->eip.utf8 = malloc(strlen(eip)+1);
        memset((char*)m->cip.utf8, 0, strlen(cip)+1);
        memset((char*)m->eip.utf8, 0, strlen(eip)+1);
        strncpy((char*)m->cip.utf8, (const char*)cip, strlen(cip));
        m->cip.len = strlen(cip);
        strncpy((char*)m->eip.utf8, (const char*)eip, strlen(eip));
        m->eip.len = strlen(eip);
        size_t wrote = cmsd_map_cap_marshal(m, buf);
        free((char*)m->cip.utf8);
        free((char*)m->eip.utf8);
        free(m);
        return wrote;
}
```

This bit solves the seg. for me. 

```
size_t pack_map_with_colfer(uint32_t mapid, char* cip, char* eip, char* buf){
        cmsd_map_cap* m = malloc(sizeof(cmsd_map_cap));
        m->msgtype = (uint32_t)0;
        m->mapid = (uint32_t)mapid;
        m->cip.utf8 = malloc(strlen(cip)+1);
        m->eip.utf8 = malloc(strlen(eip)+1);
        memset((char*)m->cip.utf8, 0, strlen(cip)+1);
        memset((char*)m->eip.utf8, 0, strlen(eip)+1);
        strncpy((char*)m->cip.utf8, (const char*)cip, strlen(cip));
        m->cip.len = strlen(cip);
        strncpy((char*)m->eip.utf8, (const char*)eip, strlen(eip));
        m->eip.len = strlen(eip);
        // ====================redundant starts
        char* prefix = "2001::";
        m->prefix.utf8 = malloc(strlen(prefix)+1);
        memset((char*)m->prefix.utf8, 0, strlen(prefix)+1);
        strncpy((char*)m->prefix.utf8, (const char*)prefix, strlen(prefix));
        m->prefix.len = strlen(prefix);
        m->minseed = (uint64_t)0;
        m->maxseed = (uint64_t)0;
        // ====================redundant ends
        size_t wrote = cmsd_map_cap_marshal(m, buf);
        free((char*)m->cip.utf8);
        free((char*)m->eip.utf8);
        free(m);
        return wrote;
}

```

Try it with cip="2001::1", eip="2001:2", mapid=1, buf will be the usual buf to write to.

**Comment by pascaldekloe** [comment]
Ah, so `prefix.len` is not initialized. You can simply use calloc(3) instead of malloc(3) to prevent this type of mistake in general like `cmsd_map_cap* m = calloc(sizeof(cmsd_map_cap));`.

**Comment by ks228** [comment]
Thanks, appreciated.

**Comment by pascaldekloe** [comment]
No need for the string memory allocations b.t.w.. The following will be much faster.

```C
        m->cip.utf8 = cip;
        m->cip.len = strlen(cip);
        m->eip.utf8 = eip;
        m->eip.len = strlen(eip);
```

You can also try to reuse the `cmsd_map_cap` for peak performance. ;-)

**Comment by ks228** [comment]
Thanks, this is really helpful :-), given a huge number of colf types in my somewhat multi-tiered application.
