### ISSUE TITLE
Support fixed-size arrays

### ISSUE THREAD

**Issue by pascaldekloe** [pascaldekloe/colfer#36]
For most languages this prevents memory allocation as the content can be embedded into the struct. There are many good uses such as IPv6 addresses, UUIDs and binary signatures.

**Comment by pascaldekloe** [comment]
Version 2 will support fixed size opaque data from 1 to 32 bytes [256-bit]. C and Go support embedded arrays in a struct. For Java a `final` byte array seems most performant. Maybe the compiler could support alternative bindings, such as an unsigned integer for up to 8 bytes. Ideas are welcome at this point.

**Comment by awalterschulze** [comment]
I don't know how out of your way you need to go to support other fixed length integer types, but 128 bit would be great and using `[16]byte` for that in go would be very cool.

**Comment by pascaldekloe** [comment]
Yes, Go and C will have the fixed size arrays. I'm thinking about a compiler flag such as `-O uuid:typeX.field1,type2.field3+ipv6:type.field` for custom bindings per language, say `java.util.UUID`.

**Comment by awalterschulze** [comment]
I think it would be nice to allow field annotations, like protobuf and thrift already do.  These annotations can then be used to specify type aliases for code generation.  The generator can then decide how and if to interpret these annotations.

**Comment by lithdew** [comment]
Hello! Looking to use colfer for my next project in Go and stumbled upon the need for fixed-size arrays - has there been any progress on it so far? I'd love to lend a hand as well :smile:.

**Comment by pascaldekloe** [comment]
Hi @lithdew. The current release does not support the feature. It would not be hard to implement the most basic form, which is a byte array. If you can spare 40 hours then we could do this. I already know how.

**Comment by lithdew** [comment]
> Hi @lithdew. The current release does not support the feature. It would not be hard to implement the most basic form, which is a byte array. If you can spare 40 hours then we could do this. I already know how.

Happy to spare the time. What were your ideas for implementing it? Struggling to figure out how to fit fixed arrays into this: https://github.com/pascaldekloe/colfer/blob/master/go/Colfer.go

**Comment by pascaldekloe** [comment]
Sorry for the delay @lithdew. Fixed size arrays tend to use all bits. Therefore I think we should simply write the bytes as is in the serial.

Step (1) would be to add a field to `O` in `testdata/test.colf`, (2) add a test case to `go/gen_test.go` for that field, (3) make the tests pass by implementing the field in `go/Colfer.go`, and then (4) update the template in `go.go` to produce the code from (3).

**Comment by lithdew** [comment]
> Sorry for the delay @lithdew. Fixed size arrays tend to use all bits. Therefore I think we should simply write the bytes as is in the serial.
> 
> Step (1) would be to add a field to `O` in `testdata/test.colf`, (2) add a test case to `go/gen_test.go` for that field, (3) make the tests pass by implementing the field in `go/Colfer.go`, and then (4) update the template in `go.go` to produce the code from (3).

No worries :+1: how did you envision fitting a fixed array field into `O` in `go/Colfer.go` work exactly? If we limit it to just a few pre-defined fixed array sizes like [16]byte, [32]byte, etc. then it would be straightforward, though how about for arbitrary N representing fixed arrays [N]byte?

**Comment by pascaldekloe** [comment]
Exactly. In the schema you specify the amount of bytes for the fixed size.

```go
type Object {
        Fix [3]byte
}
```

That object would serialise `Object{Fix: [...]byte{0x1a, 0x2b, 0x3c}}` as 0x001a2b3c7f.

**Comment by pascaldekloe** [comment]
I'm not sure about the size limitations. In version 2 I put a limit on 32 bytes (256-bit), but maybe that is not enough? These days people use 512-bit cryptographic hashes for example.

**Comment by pascaldekloe** [comment]
Note that we don't have to encode the size of the byte array. The size is fixed. You can't change it, just like you can't change the type of any field (without breaking compatibility).

**Comment by lithdew** [comment]
> Exactly. In the schema you specify the amount of bytes for the fixed size.
> 
> ```go
> type Object {
>         Fix [3]byte
> }
> ```
> 
> That object would serialise `Object{Fix: [...]byte{0x1a, 0x2b, 0x3c}}` as 0x001a2b3c7f.

Though does this mean that we need to add in fields for every fixed byte array size in Colfer.go? i.e.

```go
type O struct {
    A [1]byte
    B [2]byte
    C [3]byte
    D [4]byte
    // ....
    ZZZZ [1024]byte
}
```

**Comment by pascaldekloe** [comment]
Arrays (of all types) are supported in version two now. Behind the scenes, each element is encoded just like separate fields (in similar order) would. Java uses final arrays.
