### ISSUE TITLE
No JavaScript Benchmarks?

### ISSUE THREAD

**Issue by ohenepee** [pascaldekloe/colfer#37]
Would love to see how the built-in JSON and Protobuf fare against colfer. Its kinda unfair to see C, Go, and Java make it to the benchmark games and JS stays at home. Could it be that the JS version couldn't live up to the Colfer performance promise?

**Comment by pascaldekloe** [comment]
JavaScript was added to give browsers access to backed data so that no conversion would be needed. NodeJS changes all that and I know little about it's performance characteristics. Don't expect peak results yet it should be easy to make it fast.

So how do you JavaScript benchmarks work? Would you care to give a hand?

**Comment by lewisdiamond** [comment]
I just tried running it, I could provide the code but I can't marshal + unmarshal and get the same result. It's also more than twice as slow as JSON in my benchmark.

**Comment by pascaldekloe** [comment]
Please share @lewisdiamond. I'll be happy to make it fast. No problem. You can make a pull request or mail to pascal@quies.net.

**Comment by pascaldekloe** [comment]
I have a few days off so the sooner the better @lewisdiamond. No need for a nice delivery. I just need a little help with the benchmark setup.

**Comment by lewisdiamond** [comment]
@pascaldekloe Well the problem I have right now is that the JS code generated by `colf` either doesn't work or I don't use it properly. Otherwise you just need the `benchmark` npm package and use it like this.
```
const Benchmark = require('benchmark');
const suite = new Benchmark.Suite;
const data = { //Data goes here }
const colfer = new b.bench.Bench(data) // Is this how it's supposed to be used?
const marshaled = colfer.marshal()
const stringified = JSON.stringify(data)

suite.add('Colfer > marshal', function() {
    colfer.marshal()
})
    .add('JSON > stringify', function() {
        JSON.stringify(data)
    })
    .add('Colfer > unmarshal', function() {
        colfer.unmarshal(marshaled)
    })
    .add('JSON > parse', function() {
        JSON.parse(stringified)
    })
    .on('cycle', (event) => {
        console.log(String(event.target))
    })
    .run({async: true})
    
```

**Comment by lewisdiamond** [comment]
Also, consider making the generated Javascript code actually just load a C version compiled to WASM.

**Comment by pascaldekloe** [comment]
Yes WASM sounds really cool yet that's another issue/feature.

I'm not sure where the `b.` in `new b.bench.Bench(data)` comes from. If you made a type called foo in a package called bar then it should read `new bar.Foo(data)`.

Also, I just fixed issue #40 with an int64 bug. If you use that datatype please try version 1.7.2 and/or Maven plugin 1.11.2.

**Comment by pascaldekloe** [comment]
Ah, then yes, your setup seems right.

I downloaded `benchmark.js` including its dependency `lodash.js` and I populated `test.js` with the following.
```
const Lodash = require('./lodash.js');
const Benchmark = require('./benchmark.js');

console.log(Benchmark.Suite);
```

For some reason `node test.js` prints "undefined". Do you understand why @lewisdiamond?

**Comment by lewisdiamond** [comment]
Did you download benchmark.js from there? https://raw.githubusercontent.com/bestiejs/benchmark.js/master/benchmark.js
```
 $ node
> const benchmark = require('./benchmark')
undefined
> benchmark.Suite
{ [Function: Suite] options: { name: undefined } }
```
```
$ node --version
v9.3.0
```

**Comment by pascaldekloe** [comment]
That exact file yes.
```
% node --version
v8.9.4
% node 
> const Benchmark = require('./benchmark');
undefined
> Benchmark.Suite
undefined
> Benchmark
{ [Function: Benchmark]
  runInContext: [Function: runInContext],
  Benchmark: [Circular] }
```
Now I know that is my setup and that this should work indeed. Thanks for helping out.

**Comment by pascaldekloe** [comment]
That exact file yes. Now I know this is supposed to work. Thanks for helping out.
```
% node --version
v8.9.4
% node
> const benchmark = require('./benchmark');
undefined
> benchmark.Suite
undefined
> benchmark
{ [Function: Benchmark]
  runInContext: [Function: runInContext],
  Benchmark: [Circular] }
```

**Comment by lewisdiamond** [comment]
It's likely because you don't have the lodash dependency. 
```
const Lodash = require('./lodash.js');
```
That does not fulfill the dependency requirement.
They get lodash like this:
```
var _ = context && context._ || require('lodash') || root._;
```
Try this:
```
root._ = require('./lodash')
const Benchmark = require('benchmark')
```

**Comment by pascaldekloe** [comment]
That root import did the trick and the suggested framework plays nicely. I can start tuning now.

**Comment by pascaldekloe** [comment]
The current (untuned) code compared to the native JSON.
```
marshal Colfer x 86,798 ops/sec ±0.87% (87 runs sampled)
unmarshal Colfer x 356,519 ops/sec ±0.17% (90 runs sampled)
marshal JSON x 221,298 ops/sec ±0.48% (94 runs sampled)
unmarshal JSON x 214,750 ops/sec ±0.12% (93 runs sampled)
```

**Comment by lewisdiamond** [comment]
Check out protobuf.js https://github.com/dcodeIO/ProtoBuf.js/
It's one of the only format faster than the built-in JSON on nodejs. I guess JSON must be written in C/C++. The only way to get close to it may be to use WASM or C++ bindings.

**Comment by pascaldekloe** [comment]
The ProtoBuf.js link was quite useful as a reference @lewisdiamond. I did not expect JavaScript to be 50 to 100 times slower than most languages. 😧 This basically means that if you care about performance at all then JavaScript is a no-go and we need WASM to save the day.

Colfer is a bit faster than Node's native [C++] JSON now but not by much.
```
marshal Colfer x 197,269 ops/sec ±1.02% (84 runs sampled)
unmarshal Colfer x 354,110 ops/sec ±0.26% (89 runs sampled)
marshal JSON x 220,158 ops/sec ±0.40% (93 runs sampled)
unmarshal JSON x 207,980 ops/sec ±0.69% (91 runs sampled)
```

For some reason the standard DataView/Uint8Array performs horrible. ProtoBuf.js made it's own libraries for integer and floating point encoding to compensate.

Doubling the speed with more tuning effort is quite possible yet because those numbers still look bad I'll leave things as they are for now and defer to V8 for TypedArray optimisation.

**Comment by pascaldekloe** [comment]
https://golang.org/doc/go1.11#wasm

**Comment by nightwolfz** [comment]
The JS implementation is creating functions dynamically, no surprise it's slow.
