### ISSUE TITLE
How to set a longer package name in Java?

### ISSUE THREAD

**Issue by jschneider** [pascaldekloe/colfer#4]
I tried different things. How can I set the package name to e.g. "com.cedarsoft.test.colfer"?

**Comment by pascaldekloe** [comment]
Use the p flag as in `colf -p com/cedarsoft/test`.

**Comment by jschneider** [comment]
Ok, but why is there a "package" statement in the .colf file?
I think that is a bit surprising.

I'd prefer a way to configure the package in the .colf file. Seems to be simpler than always needing a parameter.

**Comment by pascaldekloe** [comment]
The package declaration the the schema is a Colfer concept. Packages can be used to group domains.

#### Example `things.colf` file
```
package first

type Thing struct {
    Others []second.Another
}
```

#### Example `others.colf` file
```
package second

type Another struct {
        Name string
}
```

Programming languages have various ways to deal with packages or even no way at all (like ECMAScript). For Java it is common practice to have deeply nested structures. Te command `colf -p com.example things.colf others.colf` will generate the classes com.example.**first**.Thing and com.example.**second**.Another.

I kind of like the idea that the specifics for each language ar not defined in the schema itself. Instead the setup is part of the interpretation / compilation process.
