### ISSUE TITLE
Java String fields when explicitly set to null throws NullPointerException when marshal() is called

### ISSUE THREAD

**Issue by abhinavrau** [pascaldekloe/colfer#41]
I am using the latest (1.11.2) colfer maven plugin to generate Java objects for serialization and I noticed that when String fields are explicitly set to null, a NullPointerException is thrown. It looks like the generated code is generating the following code for String name **title**:

`if (! this.title.isEmpty()) {`

Can this be changed to check for null first before calling `isEmpty()`? Something like
`if (this.title!=null && ! this.title.isEmpty()) {`

**Comment by pascaldekloe** [comment]
Not checking for nil was done on purpose. See issue #17 for the discussion. Does that make sense?

**Comment by abhinavrau** [comment]
It makes sense and I see that is by design. Thanks for the reply
