### ISSUE TITLE
Integrate with Spring

### ISSUE THREAD

**Issue by umeshchordia** [pascaldekloe/colfer#46]
How can we integrate with Spring Rest Controllers

**Comment by pascaldekloe** [comment]
Spring definitely has some way to define a custom serialisation other than the default JAX-B and such. I'd define an abstract class with the marshal and unmarshal methods, use the colf(1) `-x` flag to inherit this class and then write a Spring implementation to deal with anything which matches this pattern. If you help me find the respective Spring components I can even build a little library for it?

**Comment by umeshchordia** [comment]
Please let me know what kind of component you are looking for?

**Comment by pascaldekloe** [comment]
The part of Springs API which facilitates custom bindings.

**Comment by umeshchordia** [comment]
Spring has a list of HttpMessageConverters. Are you asking about that?

**Comment by pascaldekloe** [comment]
No idea, you do your half, I'll help.
