### ISSUE TITLE
Clarification request for "Robust against malicious input"

### ISSUE THREAD

**Issue by pavelrappo** [pascaldekloe/colfer#47]
The [Features](https://github.com/pascaldekloe/colfer#features) section on the project page mentions that this serialization format is "Robust against malicious input". 

Could it be a little more detailed than that? To what degree and how this robustness is achieved?

**Comment by pascaldekloe** [comment]
The size limitations are met at all times. A parser wil not read more nor is it possible consume significantly more memory than the serial size [memory bombs].
The parser will only report the documented errors no matter the input.

This robustness comes form design considerations, careful coding and fuzzing.

**Comment by pascaldekloe** [comment]
… and for the marshaller no value or combination of values may lead to a malfored serial.

**Comment by pascaldekloe** [comment]
No byte combination may trigger reads outside the boundaries of the serial. This is a big one.

**Comment by pavelrappo** [comment]
I believe my question has been answered. Thanks.

**Comment by pascaldekloe** [comment]
The README could use a security section with a listing.
