### ISSUE TITLE
Is this used in production anywhere?

### ISSUE THREAD

**Issue by michaeleiselsc** [pascaldekloe/colfer#5]
Hi, I work for a large mobile app company that is interested in replacing JSON with something faster. The one disappointing thing is that colfer is written in Go and JS it looks like, which we can't use for iOS or Android (without a fair amount of finagling at least), so are there any plans for it to get ported to C/C++? Also, are there any companies that use it? It would be great to see a list of some companies that use or even their experiences, as that would really sell the format. How much security auditing has occurred?

The numbers on https://github.com/eishay/jvm-serializers/wiki are tantalizing, so I'm curious to hear more :)

**Comment by pascaldekloe** [comment]
Hi Michael,

The Java from Colfer is supposed to run on Adroid.
A C port is under development yet I haven't used that language for over 10
years. Some help would be much appreciated.

Yes Colfer is used by a few companies including a high volume stock broker.
Just like you they didn't mention the specifics and I don't ask. ^_^

Op 20 okt. 2016 8:14 a.m. schreef "Michael Eisel" <notifications@github.com

**Comment by pascaldekloe** [comment]
I've mistaken the e-mail notification for a PM. 😁
Anyway, security is an important factor indeed. The (un)marshalling has built-in support for size limitation. I did some fuzzing for the Go implementation with './testdata/fuzz.go'. Can you recommend any C libraries for testing?

**Comment by michaeleiselsc** [comment]
Check out the security work these guys did: https://capnproto.org/news/

**Comment by pascaldekloe** [comment]
Let's skip that kind of "work" here. 😉

**Comment by pascaldekloe** [comment]
Started a wiki to collect information.

B.t.w., after this issue was created I saw quite some activity from security experts. Was that you @michaeleiselsc and if so, would you care to share the results?

**Comment by pascaldekloe** [comment]
C++ port is up for the next milestone. (issue #10)

**Comment by michaeleiselsc** [comment]
That was not me doing the security testing :P 
Thanks for the heads up!
