### ISSUE TITLE
want generate golang header with standard way

### ISSUE THREAD

**Issue by daqingshu** [pascaldekloe/colfer#50]
would you please refer https://github.com/golang/go/issues/13560

**Comment by pascaldekloe** [comment]
What is the question @daqingshu? The title mentions something about a header. Which header do you mean?

**Comment by daqingshu** [comment]
> What is the question @daqingshu? The title mentions something about a header. Which header do you mean?

sorry, it's my fault, the colfer had generate "Code generated by colf(1); DO NOT EDIT." I missed to see it, so I close this issue.
