### ISSUE TITLE
Document limitation: Only 126 fields, ever, no removing

### ISSUE THREAD

**Issue by tv42** [pascaldekloe/colfer#51]
I wish it had been documented that a colf type cannot have more than 126 fields, ever, and this includes "deleted" fields.

(Why 126? "Each definition starts with an 8-bit header. The 7 least significant bits identify the field by its (0-based position) index in the schema." and 127 is reserved for the termination byte.)

Related, I wish https://github.com/pascaldekloe/colfer/#compatibility had explicitly said "Fields can never be removed."

**Comment by tv42** [comment]
Bah make that 127 again; 0 is a valid field, so header value 126 is the 127th field.

**Comment by pascaldekloe** [comment]
The field limit is clearly documented in the README.
> Maximum of 127 fields per data structure.

I thought the README was also quite clear on the never remove, append only, rename if you have to. Open to suggestions here. Text improvements are welcome!

**Comment by pascaldekloe** [comment]
How did you manage a struct with more than 127 fields b.t.w.? 😱 Curious as this use case might impact version 2. There the field limit is a bit higher, but not by much.

**Comment by pascaldekloe** [comment]
PING @tv42 
 … or were you just expressing wishes here?

**Comment by pascaldekloe** [comment]
Lame

**Comment by tv42** [comment]
I'm expressing an uncertainty that the README left me with. I have not even _used_ your library, much less ran into this limit. 127 fields would mostly happen with something that was changing reasonably often; I could see a copy type changing once or twice a week in an early-stage app, with fields being added and removed. It just felt like something worth documenting more clearly, as it is a very different design than other numbered-fields formats, e.g. protobuf.

Anyway, lame response too.

**Comment by pascaldekloe** [comment]
Right, so I'm dealing here with an issue based on your theoretical concerns. The concern is a huge data structure in production. If it turns out the data structure is broken, and if all of improvements are broken too, then that data structure becomes problematic after a year or so when submitted to weekly patches. This is exactly why I documented the limit as a feature.
