### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [pascaldekloe/colfer#55]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

I saw that you implemented Fuzz targets but they are currently not running as part of the CI.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by pascaldekloe** [comment]
Free fuzzing service sounds good. 😊Would be happy to pay for it too.

The integration gap is a bit scary though. Do you have a Docker image with `go-fuzz-build`, `go-fuzz` and `fuzzit`? Some large projects (like Promtheus) download and build these tools with a script on each and every build. 🤨

What would be the best way to fuzz the head continuously? Any pointers or links would be welcome.
