### ISSUE TITLE
BufferOverflowException in writeObject

### ISSUE THREAD

**Issue by JanWichniarek** [pascaldekloe/colfer#60]
Maybe I missed something, but it looks like a bug:
In Java, in generated class there is `writeObject(ObjectOutputStream out)` method which uses `buf` array of size 1024 by default. In case of `java.nio.BufferUnderflowException` size of it is enlarged 4 times.
But in case when `buf` array is too small to handle marshalled object, `java.nio.BufferOverflowException` is thrown by `marshal(byte[] buf, int offset)` method, not `java.nio.BufferUnderflowException`, so `buf` is not enlarged and `writeObject` ends with exception.

**Comment by pascaldekloe** [comment]
You are right Jan. 😬 I guess Java serialization is not a popular feature. Are you affected by this bug, or did you spot it by reading?

**Comment by JanWichniarek** [comment]
I was affected by this, but luckily I was able to find it and fix ;)

**Comment by pascaldekloe** [comment]
The may give you a performance boost too. I'll make a release shortly. Let me know if you need a backport to the current version.

**Comment by JanWichniarek** [comment]
Is this possible to have this fix when compiling schema with colfer-maven-plugin? Currently I'm using version 1.11.2. I'm not sure which version of colfer library it uses, but this fix isn't available.

**Comment by pascaldekloe** [comment]
Yes, I'll release on Wednesday, if that's OK with you?

**Comment by JanWichniarek** [comment]
Yes, that's great. Thanks.

**Comment by pascaldekloe** [comment]
The Maven plugin version 1.12 should be in central, any minute now @JanWichniarek.

**Comment by JanWichniarek** [comment]
Thanks. Unfortunately there is some problem with classes generated with this version. I will create separate issue for this.
