### ISSUE TITLE
Document uint16 better.

### ISSUE THREAD

**Issue by guilt** [pascaldekloe/colfer#61]
Why is uint16's compressed and uncompressed flipping the behavior of  (index | 0x80)? This flag sort of is the anti-pattern of what uint32 and uint64 do. It's a bit confusing.

**Comment by pascaldekloe** [comment]
The specification states "Unsigned 16-bit integer values greather than 255 also follow the header byte. Smaller values are encoded in one byte with the header flag set." which is precisely how the encoding works. Feel free to elaborate on the wiki if you feel like it.

**Comment by pascaldekloe** [comment]
About the consistency, the flag for both 16-bit integers and the larger unsigned integers is used as an optimization (to save one byte).

**Comment by guilt** [comment]
Okay, so in the larger integer cases, 0x80 bit is used to indicate not saving space :-) But in uint16, it is saving space of 1 byte. That's the inconsistency.

**Comment by pascaldekloe** [comment]
For 32-bit unsigneds, the flag uses 4 bytes instead of 5 bytes for large values. Dito with 64 bit, by having 8 instead of 9 bytes.

Even if there were inconsistencies, I fail to see the issue.

**Comment by guilt** [comment]
There's no issue. I just want this behavior of flags documented better in spec.

Also, we do not have an implementation for int16/int8. Would eventually like to make use of the flag's high bit to encode sign if required. That gives us an extra bit to use, for representing sign.

**Comment by pascaldekloe** [comment]
No need to encode the sign. ;-) Can use the exact same scheme for better performance and same size.
