### ISSUE TITLE
Option to not output go struct definitions

### ISSUE THREAD

**Issue by khlieng** [pascaldekloe/colfer#63]
Use case: existing struct with additional fields that don't need serialization.

**Comment by pascaldekloe** [comment]
Interesting idea. You are talking about Go specifically, right? Why not embed the serializable as follows?

```go
type Mixed struct {
        ColferStructX
        NonSerializable string
}
```

This way it is clear from the API which fields are serialized.

**Comment by khlieng** [comment]
Yes just Go, embedding works but makes initialization slightly less nice etc.

**Comment by pascaldekloe** [comment]
Such a language specific feature just to make initialization slightly more nice sounds like a very bad deal. 😉 What about struct tags?

**Comment by khlieng** [comment]
Not outputting struct definitions would make it possible to use struct tags.

**Comment by pascaldekloe** [comment]
There's more ways to add a tag to a struct. Sounds like a useful feature indeed. Another issue though. I'm closing this one for now. Feel free to reopen with a good reason.

**Comment by pascaldekloe** [comment]
Pull request #64 provides tags @khlieng.
