### ISSUE TITLE
Generated code doesn't compile with "illegal start of expression"

### ISSUE THREAD

**Issue by JanWichniarek** [pascaldekloe/colfer#66]
Hi,
When I define such structure:

```
type ColferA struct {
  value binary
}

type ColferB struct {
  value ColferA
}
```
then generated class ColferB doesn't compile with "illegal start of expression" and method marshalFit looks like this:
```
public int marshalFit() {
	long n = 1L + ;
	if (this.value != null) n += 1 + (long)this.value.marshalFit();
	if (n < 0 || n > (long)ColferB.colferSizeMax) return ColferB.colferSizeMax;
	return (int) n;
}
```

I'm using colfer-maven-plugin in version 1.12.

**Comment by pascaldekloe** [comment]
Thanks for the nice report Jan. Sloppy mistake. Never sacrifice readability to eliminate some redundancy! 🤬 Will publish a new release, with plugin version 1.12.1 in an hour or so. Maven central sometimes needs a few hours to sync.

I'd love to advertise the exact colfer version in the plugin version. I remember Maven having classifiers (like jdk1.4). Do you know how to do that. The classifier element is not allowed in the POM—only dependency elements can have one.
