### ISSUE TITLE
about compatibility, can you support adding a new field into the middle structure in the stream ?

### ISSUE THREAD

**Issue by lyx2017** [pascaldekloe/colfer#69]
> // Package demo offers a demonstration.
> // These comment lines will end up in the generated code.
> package demo
> 
> // Course is the grounds where the game of golf is played.
> type course struct {
> 	ID    uint64
> 	name  text
> 	holes []hole
> 	image binary
> 	tags  []text
> }
> 
> type hole struct {
> 	// Lat is the latitude of the cup.
> 	lat float64
> 	// Lon is the longitude of the cup.
> 	lon float64
> 	// Par is the difficulty index.
> 	par uint8
> 	// Water marks the presence of water.
> 	water bool
> 	// Sand marks the presence of sand.
> 	sand bool
        ****newfield uint8**   =====>>>>> We want add new field in the end of each structure. 
                                                                  But currently, colfer just support adding new filed in the course struct.**
> }
>

**Comment by pascaldekloe** [comment]
Does it? 😕 You can add any fields to the end of either structures.

**Comment by lyx2017** [comment]
I mean the **forward** compatibility. It's important in the production. 

If we don't support it, any new field has to be appended into the end of the data stream. 
This is not acceptable because the structure is grouped by the different logic. 

![image](https://user-images.githubusercontent.com/25585786/104685703-a00d2a80-5736-11eb-80ba-3161613ec5ab.png)

**Comment by pascaldekloe** [comment]
Forward compatibility is covered in issue #11. I still need a sponsor for version two. It'll take me 3 months to complete. Lemme know if you can help.
