### ISSUE TITLE
Integer overflow in generated Go code on 32 bit

### ISSUE THREAD

**Issue by OlPainless** [pascaldekloe/colfer#7]
Hi,
I used 'go get' to get the Colfer tool yesterday and tried today to generate a simple schema. Unfortunately the generated code does not compile under x86 32-bit due to uint overflow errors. Specifically the timestamp causes the issue:
`
        if v := o.From; !v.IsZero() {
		if s := uint(v.Unix()); s < 1<<32 {
			l += 9
		} else {
			l += 13
		}
	}
`

`Colfer.go:160: constant 4294967296 overflows uint`

I'm running go1.7.3 linux/386 if that helps. I've attached the .colf file and I'll gladly help test the fix!

Br.
Andreas

[schema.colf.zip](https://github.com/pascaldekloe/colfer/files/609282/schema.colf.zip)

**Comment by pascaldekloe** [comment]
That's embarrassing. Should be fixed now.
If you want to be sure all 32-bit issues are fixed please run `go test github.com/pascaldekloe/colfer`.

**Comment by OlPainless** [comment]
Excellent, everything seems to work. Thank you for the fix and for the project in general!

**Comment by pascaldekloe** [comment]
B.t.w. I just added support for uint8 which might be useful to your schema.

**Comment by OlPainless** [comment]
That will indeed be useful, thank you for that!
