### ISSUE TITLE
Dart support

### ISSUE THREAD

**Issue by vendelin8** [pascaldekloe/colfer#71]
Hi,

Awesome lib, thanks!
I'm planning to add a dart implementation. Writing it here, so if anyone else thinks about to add it, we don't do it multiple times.

**Comment by pascaldekloe** [comment]
Cool! 😀 

There are 3 milestones for adding a new language. First, we need a `./dart/gen.dart` implementation with `./dart/gen_test.dart` and friends. Once set, `./dart/gen.dart` must be generated with a `./dart.go` addition. At some point we do need a `./dart/bench` too.

Each language uses the [same structure](https://github.com/pascaldekloe/colfer/blob/v1.8.1/testdata/test.colf#L5) for testing. The tests all use the same [golden cases](https://github.com/pascaldekloe/colfer/blob/v1.8.1/go/gen_test.go#L24).

**Comment by vendelin8** [comment]
Currently I'm working on the time part, and I'm not sure about it. Dart has a microsecond precision time format: https://api.dart.dev/stable/2.12.3/dart-core/DateTime-class.html
For me it doesn't look necessary to add the missing 10bit information into a 64 bit dart int. Maybe with a cli flag to force add that field?
What do you think?

**Comment by pascaldekloe** [comment]
Feel free to drop the precision. 🙂 No need for rounding either. We can always add a flag later for those who need the precision. It would be nice if you could mention the loss in the README.md table.

**Comment by pascaldekloe** [comment]
Whoah, you pulled through @vendelin8. 😃 Not an easy task. Things look good too.

I'll try to familiarise somewhat with Dart a bit this weekend.

You seem to have some uncertainties/doubts, and Dart is completely new to me. Maybe we should release early (like this weekend) and advocate the API as experimental/unstable?

**Comment by pascaldekloe** [comment]
Colfer [will not](https://github.com/pascaldekloe/colfer/pull/72#issuecomment-1488527191) support this language. ☹️ My apologies @vendelin8.
