### ISSUE TITLE
Empty structs generates invalid Go code

### ISSUE THREAD

**Issue by HeavenVolkoff** [pascaldekloe/colfer#74]
Hello,

The following `test.colf` file:
```go
package test

type empty struct {}
```

When compiled generates invalid Go code:
![image](https://user-images.githubusercontent.com/9082460/124227932-cc004a80-dae1-11eb-94e1-52ba012fb295.png)

This seems to be a consequence of an assumption in the `go.go`'s `Unmarshal` function. Where an `eof:` label is defined regardless of there being fields that will populate the `unmarshal-field` template, where this label is actually used.

https://github.com/pascaldekloe/colfer/blob/eade5340de397878270c5487b52ee23f42cac6d9/go.go#L220-L240

**Comment by pascaldekloe** [comment]
Thank you for the detailed report Vítor. Somehow the non-empty check got lost. I will add it back again.

**Comment by pascaldekloe** [comment]
B.t.w., you can just type `colf go` (instead of `colf Go test.colf`) if you want to. The documentation is a bit fuzzy there. 😅

**Comment by HeavenVolkoff** [comment]
Hello, @pascaldekloe. Thank you for the quick answer.
However, I was under the impression that empty struct were valid values to be used with colfer.
I found this bug, because I was using colfer in a Go project with empty structs, manly as acknowledges for some remote procedure calls.
Although the generated code was invalid, removing the unused `eof` label allowed it to compile and function correctly, as far as i could test.
Would it be possible to revert this change, and allow empty structs to be accepted in colfer? Is there any shortcoming of using empty struct with colfer?

**Comment by pascaldekloe** [comment]
The empty struct encodes as a fixed single byte (0x7F). It encodes no information. Therefore I think it should not be used.

Why do you encode an acknowledge response? A zero byte payload is Colter's concept of NULL, regardless of the type. Wouldn't it be better to make your RPC setup skip NULL submission, and read zero payload as NULL again?
