### ISSUE TITLE
Generate schema from Kotlin code

### ISSUE THREAD

**Issue by rrva** [pascaldekloe/colfer#75]
Is there any tool to generate schema from Kotlin code?

There is something for protobuf that kind of works here:

https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-protobuf/kotlinx-serialization-protobuf/kotlinx.serialization.protobuf.schema/-proto-buf-schema-generator/index.html

**Comment by pascaldekloe** [comment]
There is none at the moment. Similar suggestions have been made for Java. How would edition Kotlin files be better than a schema file?

**Comment by pascaldekloe** [comment]
Closing on no response.

**Comment by rrva** [comment]
In my case I have quite a large data model already modeled in Kotlin. To jump start schema work, it would be nice to generate it. Also, I am unsure if I want to work schema-first with this data, but rather it would be nice to have the master version be the kotlin data classes

**Comment by pascaldekloe** [comment]
I have trouble seeing how migrating a large model to schema's will take more than 15 minutes of work @rrva. 😉 For such little gain there's little intent to write tool which produces Colfer schema's from Kotlin, as I'm sure it will be possible.
