### ISSUE TITLE
Bit Field Handling

### ISSUE THREAD

**Issue by kitswas** [pascaldekloe/colfer#79]
The Readme says that Colfer doesn't support enums.

So what should we do instead?  
For example, how can we write the following in Colfer?

```go
// Should be the same as the GamepadButtons enum in the Windows API.
// https://learn.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepadbuttons
// Taken from windows.gaming.input.h
type GamepadButtons enum {
	GamepadButtons_None = 0x0,
	GamepadButtons_Menu = 0x1,
	GamepadButtons_View = 0x2,
	GamepadButtons_A = 0x4,
	GamepadButtons_B = 0x8,
	GamepadButtons_X = 0x10,
	GamepadButtons_Y = 0x20,
	GamepadButtons_DPadUp = 0x40,
	GamepadButtons_DPadDown = 0x80,
	GamepadButtons_DPadLeft = 0x100,
	GamepadButtons_DPadRight = 0x200,
	GamepadButtons_LeftShoulder = 0x400,
	GamepadButtons_RightShoulder = 0x800,
	GamepadButtons_LeftThumbstick = 0x1000,
	GamepadButtons_RightThumbstick = 0x2000,
}
```

**Comment by pascaldekloe** [comment]
Hi Kitswas. Microsoft mislead you there with its name. Notice how each value has only one bit set. This API encodes buttons as bit flags. Each bit is an independent boolean. For example, a user may press both "left thumbstick" 0x1000 and "B" 0x8, for a combined bit field of 0x1008.

 https://en.wikipedia.org/wiki/Bit_field

You can encode all button activity in a single (Colfer) field.

```
type Gamepad struct {
        ButtonDownFlags uint16 // key press
        ButtonUpFlags   uint16 // key release
        // etc.
}
```

In your code you define the constants as part of the API.

```go
const (
        ButtonMenu = iota +1
        ButtonView
        ButtonA
…
```

For example, with `func act(a, b, c, d bool)` you could do the following.

```go
if pad.ButtonDownFlags == 0 {
        return // no button action
}

if pad.ButtonDownFlags & ButtonMenu != 0 {
        showMenu()
        return // don't care about other buttons with menu
}

if pad.ButtonDownFlags & (ButtonA|ButtonB|ButtonC|ButtonD) != 0 {
        act(pad.ButtonDownFlags&ButtonA != 0, pad.ButtonDownFlags&ButtonB != 0, pad.ButtonDownFlags&ButtonC != 0, pad.ButtonDownFlags&ButtonD != 0)
}

…
```

**Comment by pascaldekloe** [comment]
Colfer version 2 🚧 wires only 1 bit per boolean, i.e., 8 booleans per byte. If combined with bit field–code generation, then we'll end up with optimal efficiency with the convenience of named booleans.

**Comment by kitswas** [comment]
> The most straight-forward solution to 14 booleans is … 14 bool fields. That works 💯—no doubt. 😄

I might end up implementing just that. XD  
That isn't optimal (for now) but I'll take maintainability and convenience.

Did I mention that I love Colfer?  
I wasted over 3 days trying to integrate Google's [Protocol Buffers](https://github.com/protocolbuffers/protobuf) into my project.  
A far more streamlined workflow with Colfer took me only 6 hours to set up.

**Comment by pascaldekloe** [comment]
That is nice to hear @kitswas. 😊

I do sympathize with the stand-alone API concept, as you intend. Name assignment is merely a compile aspect now. Name changes do not affect the data itself. However, such distinction does not imply that the setup has to prevent users from utilizing schemas as a synchronization mechanism (cross-language).

Adding integer constants to version 1 could be an easy fix. I am not sure about its place in version 2 though. I don't want to introduce something obsolete from the start.

Colfer could also support bit sets like it supports data fields. You can rename any one without effect, and stay compatible when appending to the end only.

```
type ButtonFlags bitset {
        Menu
        View
        A
        B
        …
}
```

This route may also save a lot of code (generation) in version 2. C coders will generally be happy with the control and Java coders will demand getters and setters for each bit at some point in time.

JavaScript can handle no more than 32 bits with logical and. Such a limit may not be that bad, although 64 would be much nicer. 🤔

I will give this subject some more thought. Comments are welcome.

**Comment by kitswas** [comment]
> Colfer could also support bit sets like it supports data fields. 

Glad to know. The Colfer documentation I found (the Readme and the Wiki) does not mention this.

I believe they are due for an update.

**Comment by pascaldekloe** [comment]
No no. Nothing here yet. I'm thinking new features/options here. It would be nice to have something for bit flags in place, and I have some time now.

**Comment by pascaldekloe** [comment]
Thought about it plenty. Leaving bitfields to the users requires size estimation one way or the other. Things get ugly fast when the size estimate turned out to be wrong. On the other hand, conservative estimates cause dead weight in the serials. I believe the format should assign space efficiently which rules out direct bitfield access.

**Comment by kitswas** [comment]
Very true.
