### ISSUE TITLE
list of integers

### ISSUE THREAD

**Issue by nicely-dev** [pascaldekloe/colfer#81]
Please add integers (uint64 at least ;)) as types supported in lists.

**Comment by pascaldekloe** [comment]
duplicates #54

**Comment by pascaldekloe** [comment]
... and #26

**Comment by nicely-dev** [comment]
Thank you for the quick response (and for the fantastic project BTW!). However I get a "colfer: unsupported lists type "uint64" for field PAP.Management.Projects" with a one week old compiler and the doc still says "Lists may contain floating points, text, binaries or data structures.". Am I doing it wrong? (Projects []uint64)

**Comment by pascaldekloe** [comment]
Please read the issues. I write in there for a reason.

**Comment by nicely-dev** [comment]
Apologies, I misread. Keep the good work.
